### ISSUE TITLE
Produce EBI search dataset from POS

### ISSUE THREAD

**Issue by mkarmona** [opentargets/issues#1630]
EBI Search team needs two datasets:

1. Associations overall direct annotated with approved gene symbol and disease name
2. Platform evidence where data source == `ot_genetics_portal` also with same annotations as the above one

One suggestion to execute this is a command-line BigQuery outputting the results into another bucket in JSON lines. The way to save a query to a straight bucket can be checked [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements#exporting_data_to_csv_format).

Partially complete (27 Jan 2022) there is a ETL step `ebiSearch` which generates these outputs.

**Comment by cmalangone** [comment]
First release:
https://github.com/opentargets/platform-etl-backend/pull/177

**Comment by cmalangone** [comment]
The first release is 21.09.
It is a draft. Need to review with @andrewhercules

**Comment by andrewhercules** [comment]
Thank you @cmalangone! 😄 

I have taken a look and the files generated in the `ebisearchAssociations` directory are great and exactly what the EBI Search team require to index our data under their "Gene-Disease Associations" --> "Open Targets" category. 

![Screenshot 2021-09-27 at 16 03 20](https://user-images.githubusercontent.com/7490258/134934607-0ac6ceda-54ab-4df2-9e86-4855ce3456db.png)

For the files generated in the `ebisearchEvidence` directory, the EBI Search team will require more fields in order to recreate the current view:

![Screenshot 2021-09-27 at 15 54 50](https://user-images.githubusercontent.com/7490258/134933194-848e2149-9ed9-48ca-9467-33794227fa62.png)

["ESR1" search results visible in the "Gene-Disease Associations" --> "Open Targets Genetics" category](https://www.ebi.ac.uk/ebisearch/search.ebi?db=opentargets_genetics&query=ESR1&size=15)

Can we please update `platform-output-support` and generate the `ebisearchEvidence` dataset with the following fields using the `ot_genetics_portal` evidence dataset?

`evidence.targetId`
`evidence.target.approvedSymbol`
`evidence.diseaseId`
`evidence.disease.name`
`evidence.diseaseFromSource`
`evidence.studyId`
`evidence.variantId`
`evidence.score`

**Comment by andrewhercules** [comment]
I am moving this ticket to the 22.02 release.

Currently, `platform-output-support` generates search index files suitable for the Platform data. However, we need to update the scripts to utilise the Genetics Portal evidence in order to build the search index files for the Genetics Portal data.
