### ISSUE TITLE
Associations page filters not resetting

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1633]
There appears to be a bug in the UI where the association page filters do not reset if a user is on a target associations page, applies filters, and then searches for another target. Instead of resetting, the same filters are applied to the new search, causing blank heat maps. Please see below for an example.

Step 1: user visits the CCND1 associations page and applies a filter to see associations with "Project Score" evidence
![Screenshot 2021-07-12 at 12 50 26](https://user-images.githubusercontent.com/7490258/125283706-9264e600-e310-11eb-9024-445b81d25e30.png)

Step 2: user enters IL2RA in the search bar
![Screenshot 2021-07-12 at 12 50 42](https://user-images.githubusercontent.com/7490258/125283844-b32d3b80-e310-11eb-8a52-e9413e4f049e.png)

This issue does not happen with the the disease associations page or when switching between a target and disease associations page — in both cases, the filters reset correctly.

**Comment by andrewhercules** [comment]
Rescoped to 21.11 release due to complexity of task

**Comment by d0choa** [comment]
Based on discussions, no work expected on this for 22.02

**Comment by LucaFumis** [comment]
Thought this could be a quick win, but took a bit of experimenting. 
Refactoring of the code to fully match the disease page does work, but breaks the sub-tabs navigation (heatmap / bubbles / graph). 
Instead, refactoring the `<Route>` child to a component prop (like in the `<RoutingTabs>`, used in the disease page) appears to work. 

In the Netlify preview, the `bubbles` and `graph` views break due to CORS issues (to my understanding), but the tabs themselves seem to work OK.

**Comment by LucaFumis** [comment]
The proposed solution/approach has been discarded. AOTF, with the new page layout, will address the issue (also there probably won't be any facets).

Probably safe to close the issue.

**Comment by prashantuniyal02** [comment]
Closing as mentioned by Luca.
