### ISSUE TITLE
ETL should be to read a list of paths as input parameter

### ISSUE THREAD

**Issue by cmalangone** [opentargets/issues#1700]
The current version of the ETL reads a single path for resource
Eg.
```
evidences {
   inputs {
    raw-evidences {
      format = "json"
      path = ${common.input}"/evidence-files//*"
    } ...
```

If the path doesn't match a single path, the current implementation forces us to add a new field.
For instance if there is an "external" or "private" evidence in a different path we cannot add it.

The solution is allow path to have a list of String.

```
val paths = List(a, b, c)
ss.read.json(paths:_*)

or

spark.read.format(...).load(paths: _*)

```

**Comment by ktsirigos** [comment]
Is there any progress on this @cmalangone ?

**Comment by cmalangone** [comment]
Yes, this is a chore we have to do in order to make flexible the config file input.
It should be done for the release 22.02

**Comment by JarrodBaker** [comment]
After discussion with @mbdebian we're going to put this on the back-burner. Right now the main use case is so that we can have private evidence files in a separate location to the public ones. Given that we already duplicate all of the public/private files in separate staging areas, we're mainly looking at a decrease in storage costs as the motivator, and this is yet to be quantified.
