### ISSUE TITLE
Add [show more] functionality to disease cross-references section

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1762]
Currently, the disease cross-reference section shows all IDs for a given source. 

For example, the cross-reference section for Noonan Syndrome:

![Screenshot 2021-09-22 at 10 44 38](https://user-images.githubusercontent.com/7490258/134336297-7f5ae8bd-930b-4f20-954c-69506b92245d.png)

Can we please only show the first 3 IDs and then use the `... [show more]` functionality that is found in the description and synonyms sections on the profile pages and search top-hit panel?

![Screenshot 2021-09-22 at 10 58 02](https://user-images.githubusercontent.com/7490258/134336479-08369875-d8ff-4600-b9e7-72e3cd986945.png)

To test the implementation, here are some diseases/phenotypes with a large number of IDs:

- Early infantile epileptic encephalopathy (Orphanet_1934) has 30+ OMIM IDs
- Cystic fibrosis (Orphanet_586) has 5 ICD10 IDs
- Asthma (EFO_0000270) has 4 MedDRA IDs

**Comment by ktsirigos** [comment]
@andrewhercules is this for 22.02?

**Comment by ktsirigos** [comment]
Not sure if something has changed here (or I am missing something), but all the examples that Andrew listed appear to have like 2 or 3 terms (instead of e.g. 30). Has something changed with the data @ireneisdoomed ?

[Early infantile epileptic encephalopathy](https://platform.opentargets.org/disease/Orphanet_1934/) (Orphanet_1934) has 30+ OMIM IDs
[Cystic fibrosis](https://platform.opentargets.org/disease/Orphanet_586/associations) (Orphanet_586) has 5 ICD10 IDs
Asthma [(EFO_0000270)](https://platform.opentargets.org/disease/MONDO_0004979/associations) has 4 MedDRA IDs

**Comment by ireneisdoomed** [comment]
Cross references are there data-wise.

Andrew initially requested: 1) to display a maximum of 3 terms and 2) to add the `... [show more]` functionality. I can see that the first point is done but not the second. Is this intended, @carcruz?

**Comment by ktsirigos** [comment]
Yes, that was what confused me and thought that for some reason it happened that we only have  2-3 terms now. So maybe @carcruz can have a look :)
