### ISSUE TITLE
Investigate PhenoDigm duplicated evidence

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1805]
**Context**
There are ca. 15000 pieces of Phenodigm evidence tagged as duplicates in the 21.09 release.

**Analysis**
The difference is originated by a difference in `diseaseFromSourceId` (field that currently is not being used), whereas the mapped disease ID remains the same.

```
(evd
.filter(F.col('biologicalModelAllelicComposition') == 'Pkdcc<tm1.1Mask>/Pkdcc<tm1.1Mask>')
.filter(F.col('diseaseFromSource') == 'Microphthalmia With Limb Anomalies')
.filter(F.col('targetFromSourceId') == 'ENSG00000162878')
.filter(F.col('targetInModel') == 'Pkdcc')
.filter(F.col('biologicalModelGeneticBackground') == 'involves: C57BL/6 * CBA * FVB/N')
.show(2, vertical=True))

-RECORD 0-----------------------------------------------------
 biologicalModelAllelicComposition     | Pkdcc<tm1.1Mask>/...
 biologicalModelGeneticBackground      | involves: C57BL/6...
 biologicalModelId                     | MGI:4438619
 datasourceId                          | phenodigm
 datatypeId                            | animal_model
 diseaseFromSource                     | Microphthalmia Wi...
 diseaseFromSourceId                   | ORPHA:1106
 diseaseFromSourceMappedId             | Orphanet_1106
 diseaseModelAssociatedHumanPhenotypes | [{HP:0000347, Mic...
 diseaseModelAssociatedModelPhenotypes | [{MP:0002116, abn...
 literature                            | [21553379, 237927...
 resourceScore                         | 44.77
 targetFromSourceId                    | ENSG00000162878
 targetInModel                         | Pkdcc
 targetInModelEnsemblId                | ENSMUSG00000024247
 targetInModelMgiId                    | MGI:2147077
-RECORD 1-----------------------------------------------------
 biologicalModelAllelicComposition     | Pkdcc<tm1.1Mask>/...
 biologicalModelGeneticBackground      | involves: C57BL/6...
 biologicalModelId                     | MGI:4438619
 datasourceId                          | phenodigm
 datatypeId                            | animal_model
 diseaseFromSource                     | Microphthalmia Wi...
 diseaseFromSourceId                   | OMIM:206920
 diseaseFromSourceMappedId             | Orphanet_1106
 diseaseModelAssociatedHumanPhenotypes | [{HP:0000218, Hig...
 diseaseModelAssociatedModelPhenotypes | [{MP:0002116, abn...
 literature                            | [21553379, 237927...
 resourceScore                         | 42.5
 targetFromSourceId                    | ENSG00000162878
 targetInModel                         | Pkdcc
 targetInModelEnsemblId                | ENSMUSG00000024247
 targetInModelMgiId                    | MGI:2147077
```

**Actions**
We should investigate the source of this duplication **since the score and the associated phenotypes can differ** between both.

**Comment by cmalangone** [comment]
@tskir @ireneisdoomed I am interested in the evolving of this ticket. 
Can you please keep me in the loop?

**Comment by d0choa** [comment]
ETL config at the time of this problem:

```
    {
      id: "phenodigm",
      unique-fields: [
        "diseaseFromSource",
        "biologicalModelAllelicComposition",
        "targetInModel",
        "biologicalModelGeneticBackground"
      ],
      score-expr: "resourceScore / 100"
    },

```

**Comment by cmalangone** [comment]
Should we add diseaseFromSourceId in the unique-fields?

**Comment by ireneisdoomed** [comment]
In my opinion, the ID used at the source is not something that should model the data.
I think we should first know where the difference is coming from, maybe some records are more trustworthy than others and we can address these duplicates in the Phenodigm parser.

**Comment by d0choa** [comment]
@ireneisdoomed do we want to do anything here?

**Comment by ireneisdoomed** [comment]
@d0choa Although I understand the priority is not high, I think we should account for this.

**Comment by tskir** [comment]
I've investigated this. Please see my report and the possible options we have.

## Cause of the issue
When converting mouse phenotypes to human phenotypes and diseases, PhenoDigm uses an algorithm to estimate semantic similarity between the corresponding ontology terms. This score is what we eventually put into the `resourceScore`. (Which is, by the way, also not ideal, because it reflects similarity between mouse and human phenotypes, and _not_ association strength between gene and disease.)

In the example which @ireneisdoomed helpfully provided, PhenoDigm contains data for two ontology terms: [Orphanet:1106](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=1106) and [OMIM:206920](https://www.omim.org/clinicalSynopsis/206920). While diesease they describe is the same (microphthalmia with limb anomalies), and they get mapped to the same EFO term by OnToma, the source terms themselves are not quite identical, which causes them to get slightly different scores from PhenoDigm (44.77 and 42.50).

## Solution A: Add `diseaseFromSourceId` to the ETL idenfitying fields

This will make it consider these two entries as separate, unique evidence strings. However, as Irene pointed out, it's questionable whether this _should_ be considered as  separate evidence, because the mapped gene-disease pair is ultimately the same.

## Solution B: Group by `diseaseFromSourceId` and store multiple values within an evidence string

The schema doesn't currently allow for this, so we would need to update it. One sensible way is to add the `cohortPhenotypes` field, the same one which is used for EVA evidence. In this way, the solution is very nice because it keeps alignment between different datasources.

However, if we do this, we have to think of a way to convert multiple scores to just one: for example, to take a mean, median, or max of them all.

## Solution C: Keep only one association with the highest score

This is a very simple solution which doesn't require updates of either ETL or the schema. Out of all associations with the same mapped disease-gene pair, we can simply only keep the one with the highest score, because, again, fundamentally they represent the same population.

@ireneisdoomed @DSuveges Please let me know what you think. As for my opinion, I definitely don't want solution A. I'm OK with B or C, leaning towards B with taking the maximum of all scores, because it's aligned with other datasources and retains the most information.

**Comment by tskir** [comment]
On the call 2022-09-16 with @DSuveges and @ireneisdoomed decided to go with solution C: it's simple to implement, doesn't result in complications of schema or ETL config, and still keeps all information which is really relevant, including for debugging purposes.

**Comment by tskir** [comment]
I've implemented the deduplication approach by enforcing uniqueness on the combination of four columns mentioned in [this comment](https://github.com/opentargets/issues/issues/1805#issuecomment-934405753). It works, but something doesn't appear quite right.

According to the latest release metrics (22.09.3), there should be 16,766 duplicated evidence in IMPC. However, after deduplication I see 250,035 lines disappear, which is about 17% of the whole evidence set. 

In case I made some mistake with PySpark deduplication, I've manually checked the approach with `awk` and `jq` and confim that everything is done correctly:

```bash
parallel "{}/impc.json.gz | jq -c '{diseaseFromSource, biologicalModelAllelicComposition, targetInModel, biologicalModelGeneticBackground}' | sort | uniq -c > {}/unique-count" ::: 00-before 01-after
```

Indeed, there is a lot of duplicated evidence:
```
$ awk '$1 > 1' 00-before/unique-count | wc -l
181955
```

And we can expect exactly this number of lines disappear:
```
$ awk '{if ($1 > 1) {SUM += $1 - 1}} END {print SUM}' 00-before/unique-count
250035
```

So, either I misunderstand how ETL computes duplicates, or there's something else going on. I'll continue the investigation.

**Comment by tskir** [comment]
I've updated the list of expected unique fields, and now everything is working as planned. Before the changes, the total count of evidence strings was 1,448,157; after the changes, 1,397,430.

The order of magnitude of the observe decrease of 50,727 corresponds well to our expectations. The following fields are now used to enforce uniqueness:

```python
    # Specific to IMPC.
    'diseaseFromSource',  # Original disease name.
    'targetInModel',  # Mouse gene name.
    'biologicalModelAllelicComposition',  # Mouse model property.
    'biologicalModelGeneticBackground',  # Mouse model property.

    # General.
    'diseaseFromSourceMappedId',  # EFO mapped disease ID.
    'targetFromSourceId',  # Ensembl mapped human gene ID.
```
