### ISSUE TITLE
Bibliography pipeline publication dates

### ISSUE THREAD

**Issue by eric-czech** [opentargets/issues#1935]
Is it possible to get some more details on how publications are assigned dates in the literature pipeline (https://github.com/opentargets/platform-etl-literature)?

I noticed in `gs://open-targets-data-releases/21.11/output/literature` that these datasets nearly always have publication years (approx. 1 in a million don't).  I was expecting that number to be substantially lower, so it makes me wonder if some publications are being lost when they don't have associated dates.  Is there a strategy behind this process like:

1. Use an electronic publication date if available
2. Fall back on print publication date
3. Fall back on journal publication date, if no individual publication date is available but the publication -> journal association is
4. Default to appropriate MEDLINE/PubMed/PMC acceptance and/or creation dates

We've found that something like this is necessary to get good coverage, especially for publications that are 10+ years old.  Is there something similar happening in the EPMC pipeline?

**Comment by d0choa** [comment]
@saha-shyamasree you can probably help us explain how the dates are assigned

**Comment by saha-shyamasree** [comment]
@d0choa @eric-czech : We have a number of strategy to find the publication date. For medline abstracts, their are several publication dates available. I have added a snippet from the XML of an abstract at the bottom of this comment. I have highlighted the sections used by our pipeline. We have a lookup file generated from Europe PMC database (it contains pubmed id, PMC ID, publication date etc., I am not sure how the database entries are created.). I initially look for the pubmed id in the lookup file, if the PMID is found and the PUB_DATE is not empty, I insert that value in the JSON file (JSON file submitted as part of the data submission process.). Otherwise, our pipeline tries to find the publication date from the XML, the priority of tags are as follows, PubMedPubDate, DateCompleted and then PubDate. If none of these tags are found, then the abstract's publication is set to empty but they are not excluded.

PMID     FT_ID   PUBYEAR         PUB_DATE        RESEARCH_ARTICLE_YES_NO         AVAILABILITY_STATUS     FIRST_PUBLISH_DATE
14772364         PMC2007713      1950    01/06/1950      Y       O       1950-06-01 00:00:00
14284775         PMC2195428      1965    01/01/1965      Y       O       1965-01-01 00:00:00
4158436          PMC2138079      1965    01/09/1965      Y       O       1965-09-01 00:00:00
5839251          PMC2106676      1965    01/06/1965      Y       O       1965-06-01 00:00:00

<PubMedPubDate PubStatus="pubmed">
**<Year>1986</Year>
<Month>5</Month>
<Day>1</Day>**
</PubMedPubDate>
<PubMedPubDate PubStatus="medline">
**<Year>1986</Year>
<Month>5</Month>
<Day>1</Day>**
<Hour>0</Hour>
<Minute>1</Minute>
</PubMedPubDate>
<PubMedPubDate PubStatus="entrez">
<Year>1986</Year>
<Month>5</Month>
<Day>1</Day>
<Hour>0</Hour>
<Minute>0</Minute>
</PubMedPubDate>
-------------------------

**<PubDate>
<Year>1986</Year>
<Month>May</Month>
</PubDate>**

-------------------------

<DateCompleted>
**<Year>1986</Year>
<Month>08</Month>
<Day>18</Day>**
</DateCompleted>
<DateRevised>
<Year>2019</Year>
<Month>08</Month>
<Day>24</Day>
</DateRevised>

----------------------------------

**Comment by saha-shyamasree** [comment]
For full-text, we look for the publication date from the lookup file as mentioned above, if not found, we set it to '1900-01-01'. Again they are not excluded based on the publication date availibility.

**Comment by eric-czech** [comment]
Thanks @saha-shyamasree, that's very helpful.  And to confirm, this logic isn't in an Open Targets repository on github correct? https://github.com/opentargets/platform-etl-backend maybe?  I wanted to make sure I wasn't missing that somewhere.

**Comment by eric-czech** [comment]
Awesome, thanks again @saha-shyamasree.
