### ISSUE TITLE
genetics-api fails to restart

### ISSUE THREAD

**Issue by forus** [opentargets/issues#2120]
genetics-app exits with 255 code on restart.

Steps to reproduce:
1. Start `genetics-app`
```
docker create -e PLAY_SECRET=secret quay.io/opentargets/genetics-api:19.05.26
> <hash>

docker start <hash>
```
2. Restart `genetics-app`
```
docker restart <hash>
docker logs <hash>
This application is already running (Or delete /srv/app/ot-genetics-api-latest/RUNNING_PID file).
```

**Comment by mbdebian** [comment]
This ticket is 2.5 years old, are we sure it shouldn't be just closed?

**Comment by mbdebian** [comment]
This issue only arises when the API container is "recycled", i.e. instead of being disposed off, it is stopped and restarted when used again.
Being the API a stateless component, we recommend following an immutable pattern when launching an instance, in the same way we do in our cloud deployments, thus, no need for further cleaning of any internal docker container filesystem state.
