### ISSUE TITLE
3 diseaseIds in 22.02 disease database have broken formatting

### ISSUE THREAD

**Issue by zdorman** [opentargets/issues#2529]
**Describe the bug**
The following 3 diseaseIds appear in the OT 22.02 disease database. Because of their formatting, they cannot be found on the OT platform. 
`//ebi.ac.uk/efo/EFO_0600064`
`//ebi.ac.uk/efo/EFO_0600078`
`//ebi.ac.uk/efo/EFO_0600088`

**Observed behaviour**
The disease pages for the following 3 disease cannot be accessed due to their diseaseId format:
EFO_0600064 - [serum lipopolysaccharide activity](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0600064)
EFO_0600078 - [Achilles tendon injury](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0600078)
EFO_0600088 - [lymphocyte:monocyte ratio](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0600088)

**Expected behaviour**
Either edit the formatting of the diseaseIds to remove the `//ebi.ac.uk/efo/` prefix, or remove the diseases from the database. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Search the Open Targets Platform for any of the disease Ids to return a 404 error (e.g. EFO_0600078)
2a. Search the Open Targets Platform for any of the disease names to return the correct result (e.g. Achilles tendon injury)
2b. Click on the correct result to return a 404 error. 

**Additional context**
* I found these while using the 22.02 disease database downloaded from the FTP server at: ftp://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.02/output/etl/json/diseases/ 
* I did NOT also check to see if these diseases appeared properly in evidences, AOTF, etc.

**Comment by ireneisdoomed** [comment]
Hi @zdorman,

The disease and phenotype entities in 22.04 are based on EFO v3.39.0. The bug you report is due to an error in their data that led to incorrect parsing on our part. You can know more about it in their issue tracker [#1456](https://github.com/EBISPOT/efo/issues/1456).

EFO has already released another version to patch it, so it is expected to be fixed for our next release in April. Additionally, we have enforced our validation steps to identify and prevent these errors from happening.

Thank you very much for reporting!
