### ISSUE TITLE
Add tests to changes to the JSON Schemas

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2600]
As a **member of the data team** I want **to make sure that changes in a part of the JSON schema don't cause errors in the validation handled by a different part of the schema** because **<reason>**

## Background

If we take the disease/target object as an example, its schema has more than 2000 lines as we define cases for each of the sources of evidence.

JSON schemas are human readable, but at the same time it is not unreasonable to make typos when making changes to it.

For example, by extending the schema to add `ot_crispr_validation`, we can introduce errors that make the schema no longer valid for a Genetics Portal evidence.

## Tasks

We can set up Travis to test that some JSONL examples do not fail validation. We would find examples for different evidence sources, probes, TEPs,...

If a change in the schema results in a bad formatting of the whole object, the evidence will fail.

**Comment by DSuveges** [comment]
In a way we such testing would mean maintaining a set of json objects that cover all the cases captured by the schema. Practically having one evidence from each data source, one TEP one interactions and so on. It is not too complicated to assemble such set and include in the travis file or use pytest (eg. if we want to test for failure).

**Comment by d0choa** [comment]
@DSuveges executive decision?

**Comment by DSuveges** [comment]
I see very minor risk in not testing for this (I can't recall any failure due to unintended modification in the schema of `a` datasource while working on schema of datasource `b`), however building (and maintain) a solid process for this would be quite expensive. On the other hand we already having tests for each schema ensuring they comply to the schema of the json schema.

I more inclined closing this ticket.
