### ISSUE TITLE
Tracking initial discussion & action points around the Platform AOTF project 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2621]
This is ticket is created to start tracking discussion & action points around the Platform AOTF project.

## Background 

David, Carlos and Annalisa initiated a brainstorming discussion on how the Platform Heatmap could be modified to improve the users' experience. 

This discussion is historically based on ideas previously developed by some members of the Core Team. see 2019 prototype below

![14FB4BD4-7620-4BC4-A681-43A418FB8BF7.jpeg](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/aeb455ce-f784-4c94-ac9a-46fd0ec069b4)

**Comment by buniello** [comment]
## Task
-- As a first step, we will focus on implementing the Heatmap (disease fixed). 
We discussed exploring different visualisation options (@carcruz ).
Main specifications of the page are listed below (with first sketch, to be followed by real prototypes).

1) Fix disease as starting point
2) Show an association score for each datasource
3) Add weights (dynamically changing)
4) Decide on a "showmore" option: both pagination and scrolling options have been discussed, with pro and cons. e.g. how are the filters going to be visualised if scrolling page option is chosen?
5) Add 20 datasources as headers + legend for datatypes (see Gareth's original design)
6) Subset rows
7) Set option for cells to be clickable (evidence view/filters will show upon clicking - this part is TBD)
8) Choose a color gradient for scores increasing in value
9) Columns need to be sortable
10) Add a search box that provides option to search for every page component/item
11) Add the option to download the table -- and other component? (tbd)

![IMG_7864.jpg](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/526cea9f-0c5a-4891-a4d8-1194e8502997)

**Comment by buniello** [comment]
Example #1 
of API query that can be used to prototype scoring gradient and weights (e.g. for genetic constraint and subcellular location). 
NOTE: for subcellular location, we would probably want a simple annotation like CELL MEMBRANE -y/n.

query targetConstraint{
  targets(ensemblIds: ["ENSG00000143631","ENSG00000160712"]){
    approvedSymbol
    geneticConstraint{
      constraintType
      upperRank
      upperBin6
    }
    subcellularLocations{
      location
      source
    }
  }
}
**response:**
{
  "data": {
    "targets": [
      {
        "approvedSymbol": "FLG",
        "geneticConstraint": [
          {
            "constraintType": "syn",
            "upperRank": null,
            "upperBin6": null
          },
          {
            "constraintType": "mis",
            "upperRank": null,
            "upperBin6": null
          },
          {
            "constraintType": "lof",
            "upperRank": 19099,
            "upperBin6": 5
          }
        ],
        "subcellularLocations": [
          {
            "location": "Cytoplasmic granule",
            "source": "uniprot"
          },
          {
            "location": "Cytoplasmic bodies",
            "source": "HPA_main"
          }
        ]
      },
      {
        "approvedSymbol": "IL6R",
        "geneticConstraint": [
          {
            "constraintType": "syn",
            "upperRank": null,
            "upperBin6": null
          },
          {
            "constraintType": "mis",
            "upperRank": null,
            "upperBin6": null
          },
          {
            "constraintType": "lof",
            "upperRank": 8428,
            "upperBin6": 2
          }
        ],
        "subcellularLocations": [
          {
            "location": "[Isoform 1]: Cell membrane",
            "source": "uniprot"
          },
          {
            "location": "[Isoform 2]: Secreted",
            "source": "uniprot"
          },
          {
            "location": "[Soluble interleukin-6 receptor subunit alpha]: Secreted",
            "source": "uniprot"
          }
        ]
      }
    ]
  }
}

**Comment by d0choa** [comment]
The above query could be used as the inception of the Prioritisation panel (heatmap?).

The production API allows querying multiple targets at the same time. For this use case, the targets to query will be the ones returned by the main association heatmap. The intention would be to build a complementary set of columns that inform about different target (not disease) properties that make it more or less appropriate for drug discovery.

From the above query, we could build 2 columns:

- Genetic constraint: Informs about how much the target tolerates mutations in natural populations (gnomAD). We can either build a colour gradient from "upperBin6" or from "upperRank". The more constrained they are the worse targets they are in principle. It might be that we need a colour gradient that goes from bad (e.g. red) to medium (e.g. yellow) to good (e.g. green) for these kinds of columns
- Membrane or secreted protein: This makes a target amenable to being targeted with an antibody. Any target with the subcellular location terms `SL-0039` or `SL-0243` would qualify for this column which will become a boolean. Qualifying for these columns is a positive thing, otherwise is neutral. Note: `termSL` need to be added to the above query

This is just a first pass suggesting 2 columns on what will eventually become a list of potentially 10-20 columns. As seen in this example, the data can be a mixture of booleans and gradients with different combinations of positive, negative or neutral information. The current API is very raw and requires some data parsing to extract the right information. At a later stage, we will precompute these fields, so no FE logic will be required to generate the table.

**Comment by d0choa** [comment]
scoping finished
