### ISSUE TITLE
Investigating the possibility to add TWAS results to the Gene/Study pages in OTG

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2630]
This ticket is created to initiate a discussion within the Open Targets Genetics team on whether there is scope to add TWAS results to Gene/Study pages - following up from a request from BMS on 8-6-22.

Once such decision is made, we can start raising issues on how to implement integration and visualisation of TWAS in the Portal.

**Comment by Daniel-Considine** [comment]
https://www.nature.com/articles/ng.3367
That's the original paper for the PrediXcan methodology I used for TWAS previously. Since then Haky's group has developed MetaXcan (https://github.com/hakyimlab/MetaXcan) which doesn't require individual level data and can be run on just summary statistics. I'll have a look through the recent literature to see which methods are most suitable for our needs.
