### ISSUE TITLE
S3 dataset for associationsByDatatypeIndirect does not correspond with FTP file 

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2661]
AWS pulls our data from FTP to serve it as a public dataset in https://registry.opendata.aws/opentargets/

A user in the [community site](https://community.opentargets.org/t/questions-about-the-22-06-dataset-overlap-in-disease-terms-multiple-entries-for-disease-gene-associations/698) has reported that for 22.06, the data in 

`s3://aws-roda-hcls-datalake/opentargets_latest/associationbydatatypeindirect/`

does not correspond with the data in:

`ftp://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.06/output/etl/parquet/associationByDatatypeIndirect`

The data on our FTP seems to have the right format but not the one on the AWS. Although this is beyond our codebase, it would be good to try to resolve it so we can ensure data in S3 is correct.

I believe all code to pull our data should be publicly available here:
https://github.com/aws-samples/data-lake-as-code/
From what I see there are several branches that might be relevant

**Comment by d0choa** [comment]
I believe this is their process:
https://github.com/aws-samples/data-lake-as-code/blob/roda/scripts/ssmdoc.import.opentargets.latest.json

**Comment by mbdebian** [comment]
I've reviewed their repo and, as far as I can see, although they start with a clean local folder, as you can see [here](https://github.com/aws-samples/data-lake-as-code/blob/50f57f5b4b81773dfd0a67ab393fe10285899277/scripts/ssmdoc.import.opentargets.latest.json#L23-L24), when it comes to syncing the download to the Open Targets Source bucket, it always goes to the same destination and, as pointed out by @DSuveges , the data is not mirrored, but aggregated, as no _--delete_ parameter is used for the synchronization process.
I have submitted the following PR, aws-samples/data-lake-as-code#25, explaining the issue and implementing the operation as a mirroring process, instead of an aggregation.
