### ISSUE TITLE
Improve forest-plot user experience

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2667]
**Link to preview the visualization:** https://deploy-preview-25--ot-genetics.netlify.app/variant/1_154453788_C_T

**Suggested improvements**

- Initial state (on load) does not show any help text or reference about the visualization
![Screenshot 2022-07-12 at 12.08.01.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/8552f4a3-5a99-40f9-a879-efdb7671ab93)

- Category colors do not match between the forest-plot and the previous PheWAS chart
![Screenshot 2022-07-12 at 12.10.12.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/cbd17355-212e-4748-aa87-f84085e16e33)

- Loose of context when scrolling horizontally 
![Screenshot 2022-07-12 at 12.13.03.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/e1e9ee5d-a36c-46be-9f4a-ca4b7d0c8572)

- X-Axis overlaps the chart content
![Screenshot 2022-07-12 at 12.11.28.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/01c25d05-841c-433e-a0f9-6e3ca5393af7)

**Comment by d0choa** [comment]
cc @RobinM-code @BjornWouters

**Comment by buniello** [comment]
-Suggestion on the comment:  Initial state (on load) does not show any help text or reference about the visualization
We could add a table subtitle "Forest Plot" (similar to screenshot)

![Screenshot 2022-07-12 at 15 27 09](https://user-images.githubusercontent.com/30833755/178515865-12b983d3-c14a-4768-8ad5-2d701e30d1c5.png)

- Additional comment on the colour inconsistency feedback: 
In the forest plot, the first trait added to the search is always blue, second is orange and third is green. This pattern can result into confusion for the users, who most probably will try to find a link between these colours and the ones plotted in the PheWAS chart.
I agree with Carlos that matching the trait colours in Forest Plot with the ones in the PheWAS chart will improve the user experience.

**Comment by RobinM-code** [comment]
Hi @carcruz, @d0choa and @buniello,

We like to work on the suggest improvement for the forest-plot but noticed the development API (https://open-targets-genetics-dev.ew.r.appspot.com/graphql) is not working correctly. This makes that no data is shown when we do local development with yarn. This of course makes it difficult to make changes to the forest-plot.

**Comment by carcruz** [comment]
Hello @RobinM-code, yes the development API is down at the moment. You can use the production API (https://api.genetics.opentargets.org/graphql), just change the API endpoint in the [config file](https://github.com/opentargets/ot-ui-apps/blob/main/apps/genetics/src/config.js).

The backend team is working to have a dev endpoint as soon as possible and it will be replaced to https://api.genetics.dev.opentargets.xyz/

**Comment by RobinM-code** [comment]
Thanks for the quick reply @carcruz!

**Comment by RobinM-code** [comment]
@carcruz @d0choa @buniello 

We made a PR to improve on these issues. https://github.com/opentargets/genetics-app/pull/214
I hope this is what you had in mind. Please let us know if there are any other improvements to make.

**Comment by carcruz** [comment]
Thank you, @RobinM-code. 
The genetics repository will be deprecated this week to enforce the monorepo implementation. To review the changes, can you address them in the [ot-ui-apps repo](https://github.com/opentargets/ot-ui-apps) ?

**Comment by RobinM-code** [comment]
Of course! Here is the PR for the ot-ui-repo: https://github.com/opentargets/ot-ui-apps/pull/31

**Comment by buniello** [comment]
@RobinM-code - thank you for the fixes! All looks good - I just have a questions on the traits colour code.

I can see you have adopted the same code as PheWAS for the search functionality; however, the colours in the forest-plot still do not match with the colours plotted in PheWAS and shown in search box.
e.g. below

<img width="1332" alt="Screenshot 2022-07-19 at 10 25 19" src="https://user-images.githubusercontent.com/30833755/179727992-bbc205d6-b732-4404-a0de-aba6c7dff4f5.png">

Infectious disease is green in PheWAS -- but forest-plot and list of sub-traits are still shown in blue.
Would it be at all possible to completely harmonise the colour codes, so that data for infectious diseases would be plotted in green with a green list of sub-traits?

**Comment by RobinM-code** [comment]
@buniello Thanks for the good catch! Completely missed that. It should be fixed now.

**Comment by buniello** [comment]
yes - all good now! Thanks @RobinM-code

**Comment by buniello** [comment]
@RobinM-code - @carcruz has identified an additional minor thing in the forest-plot: when hovering, the popup view is covering the axes at the top. see arrow in pic:
![Screenshot 2022-07-21 at 09.36.41 2.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/650f29ab-e59f-4760-9d1d-fdd87858b1cc)
It's minor but worth pointing out I guess.

**Comment by RobinM-code** [comment]
Thanks, it should be resolved now.

**Comment by buniello** [comment]
Thank you @RobinM-code

**Comment by buniello** [comment]
Hi again @RobinM-code! 
Your [nice forest plot ](https://genetics.dev.opentargets.xyz/variant/1_154453788_C_T) has undergone an additional UX testing and one small additional thing came out.
Would it be possible to harmonise the plot text/font style with the one displayed for the 
neighbour PheWAS plot? 

I am referring to the `plot title`, subtitle `Add a trait category to compare` & `trait` `P-value` headers (these don't need to be bold either please).
Please also see pic below:
![Screenshot 2022-09-05 at 09.53.19.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/908186d5-4243-496e-80d4-1a5cc5514776).

Can you help with this task please?

**Comment by RobinM-code** [comment]
Hi @buniello,

I created a PR that updates the styling of the title, subtitle, trait & p-value headers (and axis header). https://github.com/opentargets/ot-ui-apps/pull/52

The reason why I chose a sub-heading for the 'forest plot' title was because of the PheWAS table that is below the forest plot. I think having a 'normal' title (like I now created in the PR) could create the impression that this table only belongs to the Forest Plot (while it also belongs to the PheWAS plot), you might want to think about this.

Here is a preview of the updated styling: 
![image](https://user-images.githubusercontent.com/76998782/188425061-b7305b43-3350-45ec-a432-a0bc2be65be1.png)

Please let me know what you think.

**Comment by buniello** [comment]
Thank you @RobinM-code, that looks really nice.
