### ISSUE TITLE
Fix handling case vs case GWAS studies

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2669]
## Description of the problem:

A @bruno-ariano noticed that some studies sourced from GWAS Catalog breaks the fine-mapping pipelines. When investigating the issue it was apparent that the problem was caused by a special set of GWAS studies (~27 of them), which studies case vs case settings. An example study: [GCST90016604](https://www.ebi.ac.uk/gwas/studies/GCST90016604). In this case two diseases Bipolar disorder vs ADHD tested against each other.

The problem comes when the v2d pipelines parses the `initial sample description` of the GWAS Catalog Study table. In this field it is described that samples from two disease cases were investigated: "20,352 bipolar disorder cases, 19,099 ADHD cases" Rendering this study as "case/control" design, with number of cases 39451, BUT the total sample size is the same, which causes problems downstream. 

## Proposed solution:

Upon parsing the study table, when the number of cases == total sample size, delete the number of cases field. The pipelines will then handle the study as continuous trait study.

## Implementation:

This ticket will be covered as part of the v2d streamlining effort.

**Comment by bruno-ariano** [comment]
As @DSuveges said the problem arise when a study is reported as case/control but has just case number and no controls. This generate an error in the pipeline here:
https://github.com/opentargets/genetics-finemapping/blob/ed7146900518562f4513b6e24749a9089412d039/finemapping/credible_set.py#L282 
Where there is a division by zero problem (the pop_cases is 1). 

Most of the 27 studies that are case-case GWAS analysed here https://www.nature.com/articles/s41588-021-00787-1.  In this paper the authors apply a new method to compare disorders with a common symptoms (e.g. schizophrenia and bipolar disorder)

I suggest to not treat these studies as continuous but to exclude them until it is clear how to interpret the result. This is because significant SNPs (even though have a beta score) are characteristic of one disease instead of the other similarly to a case-control study. The directionality however is not clear how to interpret it

**Comment by d0choa** [comment]
@DSuveges?

**Comment by DSuveges** [comment]
This logic is not yet implemented, however, this sounds like a study level QC flag. For the sake of completeness, the associations from these studies can be pushed through PICS. So I would recommend implementing this flag, then downstream processes can observe the flag and exclude from processing. 

But I would not drop these studies completely. Although the interpretation might be complicated.

**Comment by DSuveges** [comment]
This is not an issue anymore. The study curation removes these studies.
