### ISSUE TITLE
Dev environment - Bug report on study page for GCST90002374 (internal server error)

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2709]
In the dev environment, the study page for [GCST90002374](https://genetics.dev.opentargets.xyz/study/GCST90002374) does not work and returns an **internal server error**.
The [same page](https://genetics.opentargets.org/study/GCST90002374) works in production.

**Query failing is:**
```

query GenePageQuery {
  manhattan (studyId:"GCST90002374") {
    associations {
      variant {
        id
      }
      bestLocus2Genes {
        gene {
          id
        }
      }
    }
  }
}
```
**Response**
```

{
  "data": null,
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "manhattan",
        "associations",
        789,
        "bestLocus2Genes",
        0,
        "gene"
      ],
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by JarrodBaker** [comment]
This issue comes from a bad value in the Manhattan table.

When I execute the SQL query:

```
SELECT
    gene_id,
    gene
FROM genes AS g
ANTI RIGHT JOIN
(
    SELECT
        study,
        arrayJoin(flatten(groupUniqArray(top10_genes_l2g_ids))) AS gene
    FROM manhattan
    WHERE (study = 'GCST90002374') AND notEmpty(top10_genes_l2g_ids)
    GROUP BY study
) AS m ON g.gene_id = m.gene
FORMAT Vertical

Query id: fdc94954-5e9f-426b-8ba7-5d5dfd5e559b

Row 1:
──────
gene_id: 
gene:    ENSG00000180953

```
There is gene `ENSG00000180953` in the Manhattan data that is not present in the genes index. This can be seen by running the API query:

```
query badgene {
  geneInfo(geneId: "ENSG00000180953"){
    id
  }
}
```
Which returns
```
{
  "data": {
    "geneInfo": null
  }
}
```
The root cause of this is that the genes entering the ETL from the L2G step are not validated to ensure that we only ingest valid items. 

Until there are steps in place to ensure that all the sets are working from a common dictionary of terms we will continue to see these errors.

**Comment by buniello** [comment]
`ENSG00000180953` encodes for ST20, a LncRNA in the current Ensembl release: [https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000180953;r=15:79898840-79923702](url), 
 - which explains why it did not make it to the L2G.
 
`ENSG00000180953` was possibly indexed as a protein coding gene in the previous Ensembl release, which explains why we have a gene page for [ST20 in production](https://genetics.opentargets.org/gene/ENSG00000180953).
