### ISSUE TITLE
Investigate data license across Platform and Portal

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2751]
Can we fully investigate whether we can qualify for a [CCZero](https://opendefinition.org/licenses/cc-zero) (CC0-1.0) license for Platform/Portal?

Previous investigation of a partial list of our data sources:
https://docs.google.com/spreadsheets/d/1m3_eSPr2NatMVHulkbX8I8Hyt8fAu70zq416A9JgwQs/edit#gid=0

Previous EBI discussions about data licensing:
https://docs.google.com/document/d/1cRghHIxk8aWCOHuno2kPEoF21NBhu4JqPlZJtV62eSA/edit#

Further tickets might follow about the implementation and communication of the license once finalised.

**Comment by buniello** [comment]
[For my own records](https://creativecommons.org/faq/#what-things-should-i-think-about-before-i-apply-a-creative-commons-license)

**Comment by buniello** [comment]
Google Tag Manager does not recognise the CC0 HTML code - I have discussed the issue with @LucaFumis and will try to solve the problem together

**Comment by LucaFumis** [comment]
Thank you @buniello. 
Do we need a different one for PPP, or same as platform?

**Comment by buniello** [comment]
@LucaFumis: We can only licence the publicly available datasets in Platform and Genetics, so the PPP will share the Platform's licence for the public data. I hope this makes sense?

**Comment by LucaFumis** [comment]
The code generated by the CC app:
is essentially the same for both platform and genetics - only the text+link itself changes.
as it is, it breaks the page as it's not compatible with React
the styling is basic and doesn't fit with the rest of the footer.

Since it's only to display the badge with link to CC license details, I've refactored it to fit the platform footer. As it sits at the bottom of the About column, I'd go with a slightly smaller font size

<img width="1197" alt="Screenshot 2023-03-30 at 19 31 23" src="https://user-images.githubusercontent.com/8592363/229180904-87d97ba8-54bd-40fc-83fe-5ce9515081b8.png">

**Comment by prashantuniyal02** [comment]
@LucaFumis, can you create a FE release tag for these changes?
@buniello are there any other FE changes that should be part of the soft release?

**Comment by buniello** [comment]
Please liaise with Chitntan for [this](https://github.com/opentargets/issues/issues/2919) 👍🏼

**Comment by LucaFumis** [comment]
Thanks @prashantuniyal02. 
PR still pending - once this and Chintan's PR are approved and merged then we can make a new tag... I suspect it might be next week now...
When are we planning a soft release next week?
