### ISSUE TITLE
Beta in the Platform Gene Burden widget is mislabelled as Odds Ratio

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2808]
**Describe the bug**
In the Gene Burden widget on the Open Targets Platform, the numbers in the `Odds Ratio` column are actually the `Beta`.

For example: https://platform.opentargets.org/evidence/ENSG00000204385/EFO_0003898
Source data: https://app.genebass.org/gene/ENSG00000204385?burdenSet=missense%7CLC&phewasOpts=1&resultLayout=full

**Comment by ireneisdoomed** [comment]
After exploring this I've seen that Genebass always reports effect sizes with beta coefficients, as we see in their web. The error came from the bad assumption from GWASs where the size for binary traits is given in the form of odds ratio whereas for continuous traits betas are used.
This is fixed in the new evidence file: `gs://otar000-evidence_input/GeneBurden/json/gene_burden-2022-11-18.json.gz`
