### ISSUE TITLE
Updates to Clinical trial phases by ChEMBL in latest release

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2878]
ChEMBL will updates the scoring for Clinical trial phases in their latest Feb-2023 release. We need to ensure we also update the way we scoring target safety (target prioritisation) taking this change into account.

**Comment by ireneisdoomed** [comment]
As of the **data team repos**, we only process evidence so we should look out for the `clinicalPhase` field
- [ ] JSON Schema for the ChEMBL evidence is affected by this: changes in place with [#167](https://github.com/opentargets/json_schema/pull/167), we expect ChEMBL to submit evidence following the new format by next week.
- [x] Evidence parsers are not affected, this change will propagate with no impact.

As of the **back end team repos**, we process evidence, and other indices we download directly from ChEMBL, so we should chase the `clinicalPhase` (evidence) field, `maxPhase`, `max_phase_for_indication` (molecule, indications)

- [x] I don't think PIS is affected, the names of the picked fields are the same and the types of the returned datasets are not validated.
- [ ] ETL: The evidence scoring depends on the phase. To my understanding, the [function](https://github.com/opentargets/platform-etl-backend/blob/29a7250c8c68ff4110e2a71f6a28bb717a12f2aa/src/main/resources/reference.conf#L647) that factors in the phase should work with any given number (float or integer). Please confirm.
- [ ] ETL: The generation of the `molecule` dataset is affected. We need to change [this condition](https://github.com/opentargets/platform-etl-backend/blob/29a7250c8c68ff4110e2a71f6a28bb717a12f2aa/src/main/scala/io/opentargets/etl/backend/drug/Molecule.scala#L86) **Be also mindful that the schema says that `max_phase` is of string type because of the presence of nulls**
- [ ] Overall we need to make sure that the types of the columns derived from the original data are updated: `maxPhaseForIndication` and `maximumClinicalTrialPhase`. This affects both the ETL and the API.

As of the **front end team repos**, I don't know enough about the impact, but I'd chase all the references to `maxPhaseForIndication`, `maximumClinicalTrialPhase`, `clinicalPhase` inside ot-ui-apps.

**Comment by d0choa** [comment]
We need to chase the integer -> float through at least all these systems:

![image](https://github.com/opentargets/issues/assets/5097586/4a3d0a3a-100f-4ba5-8881-7ce0edd7c4c4)
