### ISSUE TITLE
HELP: [sumstat_harmoniser]main.py: error: the following arguments are required: --sumstats, --vcf, --chrom_col, --pos_col, --effAl_col, --otherAl_col

### ISSUE THREAD

**Issue by YidieLin** [opentargets/issues#2886]
**Describe the bug**
I wanted to harmonize a GWAS sumstats data, but failed when using *sumstat_harmoniser*.
my code was
```
bin/sumstat_harmoniser \
 > --sumstats stroke_eas.tsv.gz \
 > --vcf gnomad.exomes.r2.1.1.sites.18.vcf.bgz \                   
 > --eaf_col EAF \
 > --af_vcf_field AF_eas_jpn \
 > --chrom_col CHROMOSOME \
 > --pos_col POSITION \
 > --effAl_col EA \
 > --otherAl_col NEA \
 > --beta_col BETA \
 > --or_col OR \
 > --or_col_lower OR_95L \
 > --or_col_upper OR_95U \
 > --palin_mode infer \
 > --hm_sumstats test.hm \
 > --hm_statfile test.stats
```

**Observed behaviour**
*main.py: error: the following arguments are required: --sumstats, --vcf, --chrom_col, --pos_col, --effAl_col, --otherAl_col*

**Additional context**
To figure out this problem, I also used *test_data* to run the code, but still had the same error.
![图片](https://user-images.githubusercontent.com/118446714/220368357-54eb1c60-6253-41d0-bc4d-39d576964209.png)

Could someone help me with this error?

**Comment by prashantuniyal02** [comment]
Hi @YidieLin, we have a growing [community of open targets users](https://community.opentargets.org/) where you can post your queries and find answers to common technical support questions about accessing Open Targets data. 
It would be great if you could kindly repost your query on the community page.

**Comment by ireneisdoomed** [comment]
Hi @YidieLin, given the error you are getting, I have the impression the problem is in the way you are providing the parameters to the program. It's not the harmoniser that is failing, but the actual argument parser.

Note that every line of your instruction starts with `> --`, I think the parser is not picking that up and that is why the error says you are missing mandatory arguments. Can you please try to call the script in a single line and see if it also fails?

**Comment by prashantuniyal02** [comment]
Please reopen if your query is not resolved.
