### ISSUE TITLE
Metrics/documentation updates for 23.02

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2888]
# Metrics

### Priority
- **Probes & Drugs** What new data do we integrate from them? e.g. number of probes. How much of an increase is this compared to the last release?

### Nice to have
- **Literature** How many preprints/patents do we have?
- **AOPWiki** How many additional adverse outcomes do we have? (if possible: how many for which we did not previously have data?)

- Out of curiosity, why is there a drop in evidence from Europe PMC if we now have additional evidence?

# Documentation
From my list, we need to add the following to the documentation:

- [x] Additional study to Gene Burden
- [x] Update Genetics widget docs to explain QTL direction of effect?
- [x] Add AOPWiki as a data source for Safety

Anything else?

**Comment by ireneisdoomed** [comment]
## Probes

This brings the number of standardised probes to over 4,000, of which almost 1,000 are considered high quality. This is a significant increase compared to the previous release, which included ~2,700 probes.

This might not be interesting, but the difference is not only due to the inclusion of DrugMAP and VGSC-DB as sources but also due to how we integrate their data: the parsing of their data is now more straightforward, as they make available CSV dumps on top of the SQL export, which is what we used to process and was more cumbersome.

In general, not only do we have more probes, but we also have probes information for way more targets (844 vs 572).

**Comment by ireneisdoomed** [comment]
## AOPWiki

- We are adding safety information from AOPWiki to 89 targets, of which 47 are novel and are not supported by any other source.
- We are bringing 87 "new" safety events. I say "new" because these are unmapped terms, so there are cases where a different trait label is actually referring to the same condition.
- We have made an effort to map the newly introduced events to EFO for those that are applicable to humans, so we have 27 new mapped events.

**Comment by ireneisdoomed** [comment]
## Literature

Breakdown in the **evidence**:
```
+----------+-------+
|  lit_type|  count|
+----------+-------+
|Literature|5131169|
| Preprints|  97951|
|   Patents|  94120|
+----------+-------+
```

Breakdown in the **matches** (what populates the Bibliography widget):
```
+----------+--------+
|  lit_type|   count|
+----------+--------+
|Literature|12751527|
|   Patents|  861140|
| Preprints|  264780|
+----------+--------+
```

--- 
Dirty query if I need to extract the same thing in the future:
```
(
    ...:     matches.select(f.explode(f.array(f.col("pmid"), f.col("pmcid"))).alias("literatureId")).distinct().withColumn(
    ...:     "lit_source", f.regexp_replace(f.col("literatureId"), "\d+", "")
    ...:     ).groupBy("lit_source").count()
    ...:     .orderBy(f.col("count").desc())
    ...:     .withColumn("lit_type", f.when(f.col("lit_source").isin(["", "PMC"]), "Literature").when(f.col("lit_source") == "PPR", "Preprints").otherwise("
    ...: Patents"))
    ...:     .groupBy("lit_type").agg(f.sum("count").alias("count"))
    ...:     .orderBy(f.col("count").desc())
    ...:     .show(50)
    ...: )
```

**Comment by HelenaCornu** [comment]
To check my understanding: for literature, is **matches** a subset of **evidence**?

**Comment by ireneisdoomed** [comment]
@HelenaCornu No, the other way around.
Matches = all the entities (EFO/CHEMBL/ENSEMBL) that we are able to identify anywhere in the literature. 
Evidence = co-occurrences = every disease/target (EFO/ENSEMBL) pair that are mentioned in the same sentence in the literature.
