### ISSUE TITLE
Credible set not loading for some phenotypes in Open Targets Genetics

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2960]
**Describe the bug**
[As reported in the Community](https://community.opentargets.org/t/credible-set-not-loading-for-several-phenotypes/1105/2), the credible sets in the loci are not loading for several phenotypes. 

**Observed behaviour**
See this example: https://genetics.opentargets.org/study-locus/GCST006867/17_63610240_C_T
<img width="1286" alt="Screenshot 2023-06-01 at 15 45 46" src="https://github.com/opentargets/issues/assets/73692302/4b29357b-ec32-4749-ad4c-20e687367f04">

**Expected behaviour**
The credible sets should load.

**Comment by buniello** [comment]
This is linked to: https://github.com/opentargets/issues/issues/2910. In this ticket, we decided to go forward with a "quick fix", but I guess now we should refine the fix/message a bit better if the current one is confusing for users (discussed with maya and David).

- [ ] We should still display the `credible set/coloc` section, but cutting the credible set to the top 25 records when the page does not load because the `CredibleSetsGwasQtlList` API query returns an high number of lines. 

- [ ] We should then show a message saying 
` Due to a problem on our side, we are temporarily showing just the top 25 credible sets in this section`

@chinmehta @remo87 could you please take a look at this issue please?
