### ISSUE TITLE
Missing pmids in the literature input

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2974]
**Describe the bug**

Upon investigating #2692 I have noticed that there are ~9M pmids in the old[1] dataset that could not be found in the new[2]. As the dataset contains publications with no identified entities, I assume these publications were not picked up by the pipeline. **Important to highlight that these are raw datasets, prior normalising recognised entities**

When joining the two datasets by pmid I get these numbers:

```
+------+--------+
|source|   count|
+------+--------+
|   new| 5495431|
|  both|18494199|
|   old| 9899838|
+------+--------+
```

How do these missing publications look like?

```
+--------+----------+----------+------+
|    pmid|     22-01|     23-06|source|
+--------+----------+----------+------+
|10000108|1991-09-01|      null|   old|
|10000304|1992-03-01|      null|   old|
|10000454|1992-03-01|      null|   old|
|10000472|1992-04-01|      null|   old|
|10000528|1992-04-01|      null|   old|
|10000591|1992-04-01|      null|   old|
|10000670|1992-04-01|      null|   old|
|10000720|1992-04-01|      null|   old|
|10000723|1992-04-01|      null|   old|
|10000761|1992-04-01|      null|   old|
|10000835|1992-04-01|      null|   old|
|10000989|1992-05-01|      null|   old|
|  100010|1978-09-01|1978-09-01|  both|
|10001331|1992-06-01|      null|   old|
|10001922|1992-02-01|      null|   old|
|10001989|1992-02-01|      null|   old|
|10002011|1992-02-01|      null|   old|
|10002280|1992-09-01|      null|   old|
| 1000240|1976-12-01|      null|   old|
|10002674|1992-10-01|      null|   old|
+--------+----------+----------+------+
```

When investigating the old only pmids, I have noticed that none of them had abstract:
- [10000108](https://europepmc.org/article/MED/10000108)
- [1000240](https://europepmc.org/article/MED/1000240)

[1] Old raw literature input: `gs://otar025-epmc/22.01`
[2] Recent literature input: `gs://otar025-epmc/ml02`

**Expected behaviour**

I would expect that the old dataset is a subset of the new release, unless a publication got retracted.

**Comment by tsantosh7** [comment]
Hi @DSuveges 

These filters OA: Will make sure the copyrights are preserved on the article. RA: only research articles as OT were not interested in review and other articles.

The 22.01 release was a prototype I designed for integrating OT into Europe PMC infrastructure. Therefore the OA and RA filtration was not applied. This resulted in 10M more pmids. I am working on integrating the newer version of entity recognition model into our core infrastructure by the end of Mar 2024. This will ensure you will receive 10M+pmids with entity mentions from next year. Unfortunately for now due to licensing issues you will miss out this content.

**Comment by tsantosh7** [comment]
@prashantuniyal02 we are currently using OA filters to make sure the copyrights are preserved on the article. RA: only research articles as OT were not interested in review and other articles. The 22.01 release was a prototype I designed for integrating OT into Europe PMC infrastructure. Therefore the OA and RA filtration was not applied. This resulted in 10M more pmids. I am working on integrating the newer version of entity recognition model into our core infrastructure by the end of Mar 2024. This will ensure you will receive 10M+pmids BUT WITH ONLY ENTITY MENTIONS AND NOT FULL SENTENCE EVIDENCE from next year. Unfortunately for now due to licensing issues you will miss out on this content.
