### ISSUE TITLE
Incorrect links in the Chemical Probes section

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3047]
**Describe the bug**
Incorrect links in the Chemical Probes section of a target profile page in the current dev deployment

**Observed behaviour**
Invalid links in the Chemical Probes section of a [target profile page](https://platform.dev.opentargets.xyz/target/ENSG00000087085) in the current dev deployment
![image](https://github.com/opentargets/issues/assets/122870584/c174c5dc-9b90-42a4-96d4-b26cf09bdbfd)

**Expected behaviour**
These links should not be present as seen in the current production deployment of the same [target](https://platform.opentargets.org/target/ENSG00000087085).
![image](https://github.com/opentargets/issues/assets/122870584/6f9b9d9d-d52b-43fa-ae38-240ac0a14c43)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [profile page of a target](https://platform.dev.opentargets.xyz/target/ENSG00000087085) in the dev deployment
2. Scroll to "Chemical Probes" 
4. Click on links in the "Probe ID" column, it redirects to something like [this](https://platform.dev.opentargets.xyz/drug/CHEMBL140476) which leads to a 404 error as it is an incorrect link.

**Comment by ireneisdoomed** [comment]
In the new version of Chemical Probes we have 4,471 unique probes. __4,365 of them have a CHEMBL reference__ - now built with a cross reference table from the source, instead of building links using our drug index. Because of this, **we are in a situation where the link of a probe to a drug can lead to a molecule that is not part of our index.**

### How often does this happen?
- Very often. By using the new cross references table, we gain a lot of coverage.
    - Probe to ChEMBL xrefs previously: ~8%
    - Probe to ChEMBL xrefs now: ~97%
- However, 95% of these IDs are not part of the latest drug index. _This means that most of the times, the probe is not considered a drug by us._

### Options

- I wouldn't include probes in the definition of a drug if we want to keep this dataset clean of molecules without therapeutic interest such as [CHEMBL1230640](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1230640/)

- Flag invalid ChEMBL IDs as part of the ETL and drop them. This has been discussed previously, e.g. https://github.com/opentargets/issues/issues/1821 I don't want this to happen before the ETL, because it means that the probes and the drug index generation are out of sync.

- The safest and easiest option is to link out to ChEMBL, but I personally don't like this very much. I think a nice user journey would be to look inside Open Targets to see if a probe is useful for a particular disease, once the user knows that the molecule binds to their target. It is also true, that this will only happen for a minority of the probes.

- Ideally (for me), this would be handled in the FE. The user'd click on the link and we'd make a request to the respective drug page.
    - If it exists, great. Open the drug page.
    - If it doesn't, show a message in a small information box saying that the requested term is not in our drug index and suggest the ChEMBL link.

Very open for discussion on how to go around this. Option 3 is not the end of the world.

**Comment by mbdebian** [comment]
🥳
