### ISSUE TITLE
Gathering feedback on the new 'Export' and 'Pinning' functionalities in AOTF (23.12 release)

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3153]
This ticket will contain feedback from testing of the new 'Export' functionality in AOTF (23.12 release).
Any feedback welcome - user journey, style, data quality in downloaded files.
[Platform Dev Link](https://platform.dev.opentargets.xyz/)

**Comment by ireneisdoomed** [comment]
In general:
 - the new search component makes navigating in the platform feel very crisp and smooth;
 - the export box is really beautiful. Having options gives power to the user in terms of what is the exact data that they want to export

I've tested the export function in [SPATA24](https://platform.dev.opentargets.xyz/target/ENSG00000170469/associations)

### `Copy URL` button
The `Copy URL` button didn't totally work as I was expecting. However, the functionality of keeping the state is so cool that I'd perhaps make it more visible and I'd change the word `copy` to `share`
    -  If I pin a disease, the copied URL "saves" the state of the page with that parameter ✅
    - If I tweak the source weights, the copied URL doesn't reflect my changes ❌
    - A small detail is in the "URL copied" pop up message... I think it'd look nicer if the box was smaller and the text was centered like other buttons

### Data export
I did all possible combinations: pinned/unpinned diseases, with and without adjusting sources, and filtering/not filtering by data type, and using TSV/JSON exports and I didn't find any discrepancy with what I could see in the UI. It's great that the export actually works!

Other comments:
- I can't distinguish the pinned/unpinned rows when I export all of them. An extra column to indicate the pin status could be an option.
- Not clear to me what we mean by "upload rows"
- A clear all/select all in the "Associations Aggregation" drop down would be nice
- I'd rename "Associations Aggregation" to "Select associations data type". I think our user will be more familiar with this term, as that's how we refer to it in other places
- When you download a list of diseases for a target, like in my example, the column for the disease is named "symbol". This is wrong.
- The pop up message when we download data vanishes so quickly that I didn't get to read it
- The filename contains the hardcoded substring "VersionNumber"
- The column for "OT Genetics" says "otGeneticsPortal", I think we want to omit the word portal.

**Comment by buniello** [comment]
thank you @ireneisdoomed - we are discussing these in FE meeting!

**Comment by HelenaCornu** [comment]
I agree with everything Irene said!

Some additional comments or things that were different for me: 

### `Copy URL` button

I am slightly confused about whether what is going on is expected or not.

- If I open a new disease associations page, and pin some targets, they are added to the url ✅
- From there, if I switch to a different disease then the rows remain pinned (and the changed datasource controls remain changed ✅✅✅), but the targets no longer appear in the url, and if I `copy url` it doesn't have the pinned targets ❌


### Search box design

- The placement of the search box on the home page is odd weirdly high — but I think this only looks strange when you are on the home page and you don't have a search history.
- Otherwise it looks fab


### Export box design

- I really like the design of the export box! Excellent work on the styling of the advanced options.
- My only aesthetic complaint is the placement of the "Download data as" — it's weirdly spaced, particularly when you haven't opened the advanced options.
- I would have expected the export option to say the name of the disease/target rather than the ID, but since the name is still visible on the page I don't think this is a huge issue. 
- I agree with Irene about renaming the `associations aggregation`
- This is nitpicking but in the export box it's spelled prioritiZation whereas the tab is spelled prioritiSation
- I suggest the following wording for the export box:

> By default, clicking on the download tabs from this view (JSON or TSV) will export the entire association table. Please expand the advanced options to customise the export parameters.

- Also very cool that you can click away and do other things in the mean time while your file keeps downloading (in my case the pop up message was there for... a while. I definitely had time to read it). Maybe worth mentioning in the box, so people are not stuck waiting for big files to download?

### Downloaded files

- What will the version number on the downloaded file refer to? It should be “23.12”
- There are some discrepancies between the name of the datasource in the downloaded file and the name give on the web interface (EVAs). This will be confusing for anyone who hasn't interacted with our data in this format before.
- There should be a row after the datasources to indicate the weight. Since the files have the same name regardless of the options, if you download multiple files with multiple parameters you have no way of telling which is which (or if you want to remember which data source weights you used).

**Comment by prashantuniyal02** [comment]
Things to be done for this release:

- [ ] isPinned column in downloaded data
- [ ] Change "upload rows" to "uploaded rows" for PPP and remove it from Platform
- [ ] Change "symbol" to "disease" in the column for the disease when a list of diseases for a target is downloaded
- [ ] Add `Download completed` pop up message when download is complete
- [ ] Correct "VersionNumber" in the filename

**Comment by HelenaCornu** [comment]
Additional suggestion: 

- Add an option in the custom export options to limit the number of rows downloaded (minimise download time for large files)

**Comment by prashantuniyal02** [comment]
As pointed out by Helena, this seems to be a bug. Is this intentional?

1. Go to a disease aotf page (e.g. Melanoma)
2. Pin 2-3 targets (BRAF, NRAS, KIT)
3. Now in the search bar for another disease (e.g. Cancer)
4. In the new disease page, the targets are still pinned. However the URL does not display the pinned list of targets

![image](https://github.com/opentargets/issues/assets/122870584/74d5a267-4222-4634-b9fc-b88e8c72183a)

**Comment by buniello** [comment]
I also came across the bug reported by Helena above: pinned/uploaded rows do not disappear with a  page refresh. Given we still don't provide e "clear all" functionality and users need to remove the pins manually one by one (and with the uploads functionality we are talking about hundreds potentially), I believe fixing this bug is important
