### ISSUE TITLE
Correct version number in the exported file name

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3165]
**Describe the bug**

Using the export feature on the association page downloads a file with the filename: `associated-targets-30_11_2023-v_VersionNumber_.json`. However the version number 23.12 should be included in the filename. (See #3153 for detailed feedback)

**Expected behaviour**

- [x] The version number to be included in the filename.

More details to be added here after discussion with @buniello

**Comment by carcruz** [comment]
Done with https://github.com/opentargets/ot-ui-apps/pull/309

**Comment by emcdonagh-OT** [comment]
Also I found when I downloaded the JSON file, it did not contain version (name of file example: MONDO_0004975-associated-targets-04_12_2023.json) whereas the tsv did (MONDO_0008315-associated-targets-04_12_2023-v VersionNumber .tsv)

**Comment by carcruz** [comment]
@emcdonagh-OT This is done in main preview (https://main--ot-platform.netlify.app/target/ENSG00000167207/associations), and will be moved to dev preview today and production probably tomorrow

**Comment by corinabioinformatic** [comment]
Hello! I am aware this issue is closed but I did not find any related with hash associated with the downloaded files or downloaded versions. I raised a question in [OT community](https://community.opentargets.org/t/metadata-hashid-for-downloaded-files-via-wget/1409/1) already. The thing is that I would like to know if is it any way I could find the hash number per each [downloaded file at OT platform](https://platform.opentargets.org/downloads/data) or the whole bunch that I could keep with each file version I download (e.g, a csv or json file with name of the json/parque file downloaded and associated md5sum or hash, as COSMIC or Depmap or other sources have available). This would be helpful to keep some traceability in some of my reports.

Many thanks for this great work!
