### ISSUE TITLE
Review of our OpenAI based API

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#3249]
The backend MIG running our OpenAI API service, detailed [here](https://console.cloud.google.com/compute/instanceGroups/details/europe-west1/production-ai-openai-api-remig?project=open-targets-platform) has, apparently, a constant traffic of _0_ requests.

We need to verify with the platform analytics whether this service is actually being used and, in case it is, check the usage profile to verify that this backend receives no traffic from the global load balancer due to the configured CDN (if active).

The @opentargets/data-team and @opentargets/fe-team can also provide insights from the OpenAI API token usage by looking into our OpenAI dashboard details.

**Comment by ireneisdoomed** [comment]
The dashboard shows a mild usage of the app: ~600 requests in Feb, 300 in January, none in January. Moreover, the use is not constant, but rather in peaks.
<img width="683" alt="image" src="https://github.com/opentargets/issues/assets/45119610/4a27c483-dbb7-488c-8b05-d87f33a75d11">

Since we developed this, Langchain has launched a deployment service called Langserve that integrates with lambda functions in GCP. I haven't worked with it, but it is an alternative BE you might want to take into consideration.
