### ISSUE TITLE
Removing splicing QTL effect sizes to build "variantFunctionalConsequenceFromQtlId" evidence column. 

### ISSUE THREAD

**Issue by Juanmaria-rr** [opentargets/issues#3283]
## Background

The current interpretation of splicing QTL (sQTL) beta coefficients for the direction of effect assessment is not informative, where negative are interpreted as loss of function and positive ones as gain of function. 

For now we propose to remove them from the assessment for the direction of effect (DoE), so we will need to filter them out when building the evidences. 

This issue is also addressing the point 1 of the issue raised by @Daniel-Considine [here](https://github.com/opentargets/issues/issues/3282).

## Tasks

- [ ] Filter out sQTL signals before getting the one with the biggest effect (`get_biggest_effect` function) in the generation of the variantFunctionalConsequenceFromQtlId evidence column: https://github.com/opentargets/evidence_datasource_parsers/blob/ea3008a6143fd1347a3629d5869fd50438004abc/modules/GeneticsPortal.py#L84
- [ ] Run the implementation of DoE in the backend with the new data to check that the direction of effect data is properly shown. 
*(Please note that I'm not familiar with the whole process of the evidence generation, so feel free to modify my suggested tasks) 

## Acceptance tests

When direction of effect data shows no directionality from sQTL evidences.

How do we know the task is complete? 

1. Using an user case raised in genetics slack channel: 
 On the associations page for `Lymphocyte count` associated with `TYK2` ([link](https://platform.opentargets.org/target/ENSG00000105397/associations)), for the variant 19_10351837_C_T, the DoE is `loss of function | Risk`, where the loss of function comes from the `Decreased gene product level` derived from the highest effect size of sQTLs. After removing sQTL, this should appear as a `gain of function | Risk`.

**Comment by ireneisdoomed** [comment]
Looking at [the ETL code](https://github.com/opentargets/platform-etl-backend/blob/505709b2414dae5f097dfc7dea2269d663bac701/src/main/scala/io/opentargets/etl/backend/evidence/DirectionOfEffect.scala#L10), the value for `variantEffect` is based on `variantFunctionalConsequenceFromQtlId`, a value generated during the OTG evidence generation.
@remo87 @Juanmaria-rr Can you confirm this is true? If so, it's up to us to filter out sQTLs in the logic and we'd have it fixed by next release.

**Comment by Juanmaria-rr** [comment]
Yes @ireneisdoomed, I think that would be the step to include to remove the sQTL effect sizes from the DoE assessment.

**Comment by d0choa** [comment]
In #3282, @addramir and @Daniel-Considine suggested changing the logic of the aggregation. Instead of using the largest effect size, which could be problematic for poorly powered studies, use the lowest p-value. I would try to introduce this change in the same script as well.

@Juanmaria-rr will have some estimates on the impact of this change.

@buniello This will imply changing a tooltip and documentation.
