### ISSUE TITLE
Missing literature matches from ETL output

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3285]
**Describe the bug**

It has been identified that a certain drug/target connection is missing from the literature dataset. This ([32955176](https://europepmc.org/article/MED/32955176)) EuroPMC paper is available as abstract listing KRAS and sotorasib mentioned. 

> Sotorasib is a small molecule that selectively and irreversibly targets KRASG12C.

However this connection is not listed in the platform. 

When investigating the case, I could identify the input json dataset: `gs://otar025-epmc/ml02/abstract/2022_05_27/NMP_patch-total-33.jsonl`

These are the entities identified by the EuroPMC pipeline:

```
+--------+---------------------------+----+---------------+-------------+
|pmid    |label                      |type|startInSentence|endInSentence|
+--------+---------------------------+----+---------------+-------------+
|32955176|KRAS                       |GP  |0              |4            |
|32955176|Solid Tumors               |DS  |58             |70           |
|32955176|KRAS                       |GP  |49             |53           |
|32955176|cancer                     |DS  |71             |77           |
|32955176|KRAS                       |GP  |7              |11           |
|32955176|non-small-cell lung cancers|DS  |49             |76           |
|32955176|NSCLCs                     |DS  |78             |84           |
|32955176|colorectal cancers         |DS  |104            |122          |
|32955176|cancers                    |DS  |133            |140          |
|32955176|KRAS                       |GP  |72             |76           |
|32955176|solid tumors               |DS  |176            |188          |
|32955176|KRAS                       |GP  |206            |210          |
|32955176|sotorasib                  |CD  |18             |27           |
|32955176|NSCLC                      |DS  |212            |217          |
|32955176|colorectal cancer          |DS  |227            |244          |
|32955176|tumors                     |DS  |264            |270          |
|32955176|metastatic disease         |DS  |96             |114          |
|32955176|NSCLC                      |DS  |21             |26           |
|32955176|colorectal cancer          |DS  |21             |38           |
|32955176|appendiceal cancers        |DS  |75             |94           |
|32955176|melanoma                   |DS  |99             |107          |
|32955176|solid tumors               |DS  |222            |234          |
|32955176|KRAS                       |GP  |252            |256          |
+--------+---------------------------+----+---------------+-------------+
```

However, if I look at the ETL output, neither the mapped[1] nor the failed matches[2] dataset contains KRAS:

```
+--------+-----+----+--------------------+--------------------+-------------+--------+
|    pmid|pmcid|type|               label|              labelN|    keywordId|isMapped|
+--------+-----+----+--------------------+--------------------+-------------+--------+
|32955176| null|  CD|           sotorasib|           sotorasib|CHEMBL4535757|    true|
|32955176| null|  DS|              cancer|              cancer|MONDO_0004992|    true|
|32955176| null|  DS|             cancers|              cancer|MONDO_0004992|    true|
|32955176| null|  DS|  metastatic disease|      diseasmetastat|  EFO_0009709|    true|
|32955176| null|  DS|              NSCLCs|               nsclc|  EFO_0003060|    true|
|32955176| null|  DS|               NSCLC|               nsclc|  EFO_0003060|    true|
|32955176| null|  DS|               NSCLC|               nsclc|  EFO_0003060|    true|
|32955176| null|  DS|non-small-cell lu...|cancercelllungnon...|  EFO_0003060|    true|
|32955176| null|  DS|            melanoma|            melanoma|  EFO_0000756|    true|
|32955176| null|  DS|              tumors|               tumor|  EFO_0000616|    true|
|32955176| null|  DS|        solid tumors|                null|         null|   false|
|32955176| null|  DS|        solid tumors|                null|         null|   false|
|32955176| null|  DS|        Solid Tumors|                null|         null|   false|
|32955176| null|  DS| appendiceal cancers|                null|         null|   false|
+--------+-----+----+--------------------+--------------------+-------------+--------+
```

[1] gs://open-targets-data-releases/24.03/output/etl/parquet/literature/matches
[2] gs://open-targets-data-releases/24.03/output/etl/parquet/literature/failedMatches

**Expectation**

All matches identified the by the EuroPMC pipelines are expected to be in either in the failed matches or in the mapped matches dataset.

**Comment by DSuveges** [comment]
Oh, this is not good. We need to understand what is going on exactly and change that function. I know some details about that function, it was prototyped for Miguel by @tskir back in the days.

**Comment by remo87** [comment]
@DSuveges directed me to the original [issue](https://github.com/opentargets/issues/issues/1659) and the original [implementation](https://github.com/tskir/epmc-ambiguity/blob/main/prototype.py) proposal in pyspark form @tskir. I'll be reviewing those items to get more information in the feature.

**Comment by vivienho** [comment]
I processed the output of the grounding process without the disambiguation using the [python implementation](https://github.com/tskir/epmc-ambiguity/blob/main/prototype.py#L79) by @tskir and KRAS is not dropped. Therefore, the issue is likely in the scala implementation of the code.

As pointed out by @remo87, the problem is from the [disambiguate](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L109) function where the drop is happening in the filter. The issue is that the KRAS records have a value of `2` for the `minDistinctKeywordsPerLabelPerPubOverKeywordPerPub` column. This column is defined as:
```
val windowPerKeywordPerPub = Window.partitionBy(keywordColumnsPerPub.map(col): _*)

df.withColumn(minDistinctKeywordsPerLabelPerPubOverKeywordPerPub,
                  min(col(labelCountsColumnName)).over(windowPerKeywordPerPub)
    )
```
`labelCountsColumnName` is [specified](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L243) to be `"uniqueKeywordIdsPerLabelN"`which is [defined](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L546) below.

```
val cols = List(
      "key as labelN",
      "type",
      "keywordId",
      "factor"
    )

    val diseaseDf: DataFrame = transformDiseases(diseases, pipeline, pipelineColumns)
      .withColumn("type", lit("DS"))
      .selectExpr(cols: _*)

    val targetDf: DataFrame = transformTargets(targets, pipeline, pipelineColumns)
      .withColumn("type", lit("GP"))
      .selectExpr(cols: _*)

    val drugDf: DataFrame = transformDrugs(drugs, pipeline, pipelineColumns)
      .withColumn("type", lit("CD"))
      .selectExpr(cols: _*)

    val windowByTypeAndLabel = Window.partitionBy(col("type"), col("labelN"))

    diseaseDf
      .unionByName(targetDf)
      .unionByName(drugDf)
      .distinct() // fixme: can this have any effect? We're taking the union of target, disease and drug, what crossover could there be?
      .withColumn("uniqueKeywordIdsPerLabelN",
                  approx_count_distinct(col("keywordId"), 0.01).over(windowByTypeAndLabel)
      )
      .orderBy(col("type"), col("labelN"))
```

As above, the `uniqueKeywordIdsPerLabelN` column was determined over the window `windowByTypeAndLabel` where the data is partitioned by `col("labelN")`. This column was initially `"key"`, which is defined in the [transformTargets](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L428) function.

It is currently not immediately obvious how the contents of the `transformTargets` function eventually result in  KRAS having a value of `2` for the `minDistinctKeywordsPerLabelPerPubOverKeywordPerPub` column. I suspect a subtle bug somewhere in this function may be causing the issue. Potential next steps will be to go through the function code to further narrow down what the bug is.

**Comment by vivienho** [comment]
I have found the reason for the missing KRAS matches, which also affects other entities. See this [notebook](https://gist.github.com/vivienho/3b8c2c0a1bb7c23816de3c95c3e84541) describing the reason. Essentially, `minDistinctKeywordsPerLabelPerPubOverKeywordPerPub` and `minDistinctKeywordsPerLabelOverKeywordOverallPubs` in the [disambiguate](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L109) function rely on `uniqueKeywordIdsPerLabelN` which is evaluated in the [loadEntityLUT](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L515) function. However, in the [mapEntities](https://github.com/opentargets/platform-etl-backend/blob/1ff16e07188376553bedf0231ff1788f5f425ff4/src/main/scala/io/opentargets/etl/backend/literature/Grounding.scala#L162) function between these two functions, there is a filtering step to only keep `keywordIds` with `rank` 1 (the `keywordIds` with the highest `factor` for each `labelN`). Basically, labels without rank 1 are taken into account when evaluating `uniqueKeywordIdsPerLabelN` and then filtered out.

As it does not make sense to evaluate `uniqueKeywordIdsPerLabelN` before this filter, I modified the code so that `uniqueKeywordIdsPerLabelN` is evaluated after the filter. This fix had the intended result (the number of obtained matches increased). Further examination showed that while there was a net increase in the number of obtained matches, there was also a slight drop. I was able to find the explanation for this. As at this point the sum of matches and failedMatches still did not equal the matches identified by the EMPC pipeline, I also looking into the remaining matches unaccounted for. See this [notebook](https://gist.github.com/vivienho/378b7525afbe4bf735d02939309d1bec) for a thorough exploration.

After applying another round of fixes, all matches are now captured in either matches or failedMatches. See this [notebook](https://gist.github.com/vivienho/8dc7f4291a4a338532c8500e06f0eb69) for the checks.

The input literature files I used are:
```
gs://otar025-epmc/ml02/abstract/2022_05_27/NMP_patch-total-33.jsonl (This file contains the abstract with the KRAS issue: pmid="32955176")
gs://otar025-epmc/ml02/fulltext/2022_05_27/NMP_patch-26-05-2022-4.jsonl
```
Files mentioned in the notebooks can be found in `gs://ot-team/vivien/literature_exploration`
