### ISSUE TITLE
Cred Set Plot scoping ticket

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3502]
We discussed building an extra layer of visualisation to the new Platform+Genetics pages, where possible.

On example is:

- [ ] Credible Sets Plot on study page, similar to the [current OTG one](https://genetics.opentargets.org/study/GCST002222)

Assigning this to @carcruz for initial screening

**Comment by buniello** [comment]
This task has bene prioritised in team leads meeting 31/9/24 - @addramir could you please add any comment here that can be useful to the FE team (@carcruz) to start thinking about this?
A formal scoping session will be planned as well

**Comment by buniello** [comment]
We brainstormed ideas for this plot on study pages on 16th Oct 2024.
Main points:
1.  [this plot in current OTG](https://genetics.opentargets.org/study/GCST002222) can be an inspiration for a number of features (e.g. plot brushing/zooming)
2. plot should be shown by default on study page (we have plenty on space on page)
3. lines can be replaced with smarter vis if needed
4. credible set widget in study page contains fields that the new plot should show on hovering
5. it would be nice to show L2G gene names on top of plot points (if possible)

**Comment by gjmcn** [comment]
A few more details from the scoping discussion:

1. For each credible set in the study, plot a point (or line or 'lollipop') for the lead variant only: chromosome-and-position against `-log_10(pValue)`
2. Details about the corresponding credible set should be shown on hover.
3. The x-axis will show chromosomes in order (ending with X, Y), and the width of each chromosome on the axis is the length of the chromosome.
4. Should have brushing on both the x and y axis. Needed on y-axis because there is often few very high y-values and many smaller y-values.
5. Show gene (from top L2G) as clickable label next to data points. This is most important for points with largest y-value and care will be needed to prevent label overlap.
6. Show credible set table below the plot.

Consider / good to have:

- Visualise width of each credible set - e.g. could use faint bar.
- Table reacts to x-axis brushing.

**Comment by gjmcn** [comment]
Plot is done, but some polishing still required:

- Tooltip
    - tune size of tooltip to account for row spacing changes recently added to the tooltip component
    - (ideally) allow 'normal' tooltip to explain labels (as do for the column headers in the table) - tooltip values can already have normal tooltips.
- Enforce 'nice' tick values on y-axis
