### ISSUE TITLE
Adding MR/ratio beta to colocalisation

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3516]
Old OTG platform in colocalisation page there is a study beta:
https://genetics-docs.opentargets.org/faqs#why-are-betas-and-odds-ratios-displayed-inconsistently-in-the-portal

```
On the other hand, we display the study beta coefficient in the colocalisation table of the study locus page e.g. [LDL cholesterol (GCST002222) with locus around 19_44886339_G_A (rs7254892)](https://genetics.opentargets.org/study-locus/GCST002222/19_44886339_G_A). This beta is with respect to the alternative allele of a single variant, the lead variant at the top of the study locus page (i.e. rs7254892 for the LDL cholesterol study).

The reason we have decided to display the study beta it to facilitate the comparison of the direction of effect across different colocalising tissues.
```

We need something similar for our colocalisation widget.

**Comment by Tobi1kenobi** [comment]
After discussing with Yakov, the issue seems to lie with the gentropy implementation of coloc not returning a way of interpreting direction of effect. This can be resolved by generating a ratio of the [SuSiE posterior means](https://stephenslab.github.io/susieR/reference/susie_rss.html#:~:text=posterior%20inclusion%20probabilites.-,mu,-An%20L%20by) (mu) between either the GWAS and GWAS or the GWAS and molQTL.

In the instance where the two lead variants are the same, this is trivial. When these do not align a decision must be made about what the most appropriate comparison is.

Actions:

- [ ] Modify [colocalisation.py](https://github.com/opentargets/gentropy/blob/dev/src/gentropy/method/colocalisation.py) to return the ratio of mus
- [ ] Update the schema to include ratio of mus with appropriate name
- [ ] Determine how to handle edge cases
- [ ] Create a test dataset for edge cases to ensure nothing breaks downstream

**Comment by addramir** [comment]
Just as an idea: calculate the signed CLPP weighed on CLPP, similar to eCAVIAR but taking into account the sign of the betas.
E.g.:
-----|CS1 pip,beta|CS2 pip,beta
snp1 |. 0.3,+1. | 0.6, +1
snp2 |  0.5, -1. | 0.3, -1
snp3 | 0.2, +1. | 0.1, -1

signed_CLPP=sum(sign_1*sign2*pip1*pip2)/(sum(pip1*pip2))=(0.3*1*0.6*1+0.5*(-1)*0.3*(-1)+0.2*1*0.1*(-1)) / (0.3*0.6+0.5*0.3+0.2*0.1)=0.8857
 
OR

-----|CS1 pip,beta|CS2 pip,beta
snp1 |. 0.3,-1. | 0.6, +1
snp2 |  0.5, -1. | 0.3, +1
snp3 | 0.2, -1. | 0.1, +1

signed_CLPP=sum(sign_1*sign2*pip1*pip2)/(sum(pip1*pip2))=(0.3*(-1)*0.6*1+0.5*(-1)*0.3*1)+0.2*(-1)*0.1*(1)) / (0.3*0.6+0.5*0.3+0.2*0.1)=-1

**Comment by Tobi1kenobi** [comment]
Currently I've been working on a subset of the data and trying to determine how many credible sets contain variants which all have agreeing sign(beta1/beta2). Assuming most (90%+) sets have all variants in agreement, I was considering reporting, for the lead variant, the beta ratio or potentially more simply whether the eQTL effect is positive or negative relative to a positive GWAS effect (as this circumvents the choosing a variant issue and is all we really care about, right?).

I'm a little cautious about the above approach... I don't like the idea of a signed probability, personally, and whilst I can see the logic behind it, I'm afraid it may be a little confusing to explain/justify to a casual user of the portal to immediately interpret with a tooltip/FAQ.

**Comment by Tobi1kenobi** [comment]
Resolved with https://github.com/opentargets/gentropy/pull/854
