### ISSUE TITLE
Review "Fix the return type for files read from gzip archives" PR in urlzsource repo

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#837]
The Hyve have submitted a [pull request (#1) in the `urlzsource`](https://github.com/opentargets/urlzsource/pull/1) repo. 

@cmalangone will review the PR and test the changes across repos that use `urlzsource` library once the 20.02 release has been pushed to production.

**Comment by Sjoerd-van-Hagen** [comment]
Thanks @andrewhercules

**Comment by andrewhercules** [comment]
Due to challenges with LINK updates, I have moved this to the next sprint

**Comment by d0choa** [comment]
@mbdebian can you have a quick look at this old ticket for any pending actions?

**Comment by mbdebian** [comment]
The repository this ticket refers to has been archived and made read-only.
Last interaction around the reported bug and submitted PR was on June 2020, I will close this ticket as it's unlikely to be a pressing issue, in which case, a new case can be made about it within the current context (please, take into account that many changes have happened in Open Targets software ecosystem since 2020).
